/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import MenuImage from 'src/assets/images/PortofolioDetailDetails_Menu.png';
import HeroiconsOutlineXMarImage from 'src/assets/images/PortofolioDetailDetails_heroicons_outline_x_mark.svg';
import CreditCardImage from 'src/assets/images/PortofolioDetailDetails_Credit_Card.png';
import { styled } from '@mui/material/styles';
import Tabs from 'src/components/Tabs/Tabs';
import Input1 from 'src/components/Input1/Input1';
import Button1 from 'src/components/Button1/Button1';
import Table from 'src/components/Table/Table';
import Alert1 from 'src/components/Alert1/Alert1';
import ReadOnlyForm from 'src/components/ReadOnlyForm/ReadOnlyForm';
import { PortofolioDetailDetailsProps } from 'src/types';

const PortofolioDetailDeta: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
}));

const Menu: any = styled('img')({
  height: `1024px`,
  width: `278px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Navigation: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1096px`,
  left: `312px`,
  top: `32px`,
});

const Actions: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Input2: any = styled(Input1)(({ theme }: any) => ({
  alignSelf: `stretch`,
  width: `240px`,
  margin: `0px`,
}));

const Button2: any = styled(Button1)(({ theme }: any) => ({
  margin: `0px 0px 0px 12px`,
}));

const Button3: any = styled(Button1)(({ theme }: any) => ({
  margin: `0px 0px 0px 12px`,
}));

const Button4: any = styled(Button1)(({ theme }: any) => ({
  margin: `0px 0px 0px 12px`,
}));

const Table1: any = styled(Table)(({ theme }: any) => ({
  width: `1096px`,
  position: `absolute`,
  left: `312px`,
  top: `92px`,
}));

const Rectangle6: any = styled('div')(({ theme }: any) => ({
  opacity: `0.20000000298023224`,
  backgroundColor: `rgba(0, 0, 0, 1)`,
  width: `1440px`,
  height: `1024px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const DetailPanel: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `32px`,
  boxSizing: `border-box`,
  width: `590px`,
  height: `1024px`,
  left: `850px`,
  top: `0px`,
}));

const Frame44: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame43: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const HeroiconsOutlineXMar: any = styled('img')({
  height: `auto`,
  width: `24px`,
  margin: `0px`,
});

const Frame42: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const Frame120: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const CreditCard: any = styled('img')({
  height: `216px`,
  width: `344px`,
  margin: `0px`,
});

const Frame119: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `48px 0px 0px 0px`,
});

const Tabs1: any = styled(Tabs)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Alert2: any = styled(Alert1)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
}));

const ReadOnlyForm1: any = styled(ReadOnlyForm)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
}));

function PortofolioDetailDetails(
  props: PortofolioDetailDetailsProps
): JSX.Element {
  return (
    <PortofolioDetailDeta className={props.className}>
      <Menu src={MenuImage} loading="lazy" alt={'Menu'} />
      <Navigation>
        <Tabs />
        <Actions>
          <Input2 />
          <Button2 />
          <Button3 />
          <Button4 />
        </Actions>
      </Navigation>
      <Table1 />
      <Rectangle6></Rectangle6>
      <DetailPanel>
        <Frame44>
          <Frame43>
            <HeroiconsOutlineXMar
              src={HeroiconsOutlineXMarImage}
              loading="lazy"
              alt={'heroicons-outline/x-mark'}
            />
          </Frame43>
          <Frame42>
            <Frame120>
              <CreditCard
                src={CreditCardImage}
                loading="lazy"
                alt={'Credit Card'}
              />
            </Frame120>
            <Frame119>
              <Tabs1 />
              <Alert2 />
              <ReadOnlyForm1 />
            </Frame119>
          </Frame42>
        </Frame44>
      </DetailPanel>
    </PortofolioDetailDeta>
  );
}

export default PortofolioDetailDetails;
