/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/

export interface Alert1Props {
  className?: any;
}

export interface Badge1Props {
  className?: any;
}

export interface Button1Props {
  className?: any;
}

export interface CheckboxItemProps {
  className?: any;
}

export interface LoginProps {
  className?: any;
}

export interface Input1Props {
  className?: any;
}

export interface SelectionProps {
  className?: any;
}

export interface ReadOnlyFormProps {
  className?: any;
}

export interface MetricsProps {
  className?: any;
}

export interface Graph1LineProps {
  className?: any;
}

export interface Graph2LinesProps {
  className?: any;
}

export interface StackedBarProps {
  className?: any;
}

export interface MenuProps {
  className?: any;
}

export interface MenuItemProps {
  className?: any;
}

export interface CreditCardProps {
  className?: any;
}

export interface TableProps {
  className?: any;
}

export interface CellProps {
  className?: any;
}

export interface CellType7Props {
  className?: any;
}

export interface TabsProps {
  className?: any;
}

export interface TabItemProps {
  className?: any;
}

export interface DashboardProps {
  className?: any;
}

export interface MenuProps {
  className?: any;
}

export interface PortofolioDetailDetailsProps {
  className?: any;
}
